[project]
type = "lib"
version = "0.1.0"
author = ""

[runtime]
version = "{{ runtime_version }}"

[lib]
identifier = "{{ name }}"

[lib.build]
pre = "cargo build --target wasm32-wasip2"
entrypoint = "./target/wasm32-wasip2/debug/{{ package_snake }}.wasm" # The built wasm component
wit = "wit" # The package's exported WIT (its public API), relative to the project root
output = "./bin" # Jumpjet's build output
