package jumpjet:tests;

interface guest {
  register: func() -> list<string>;
}

world tests {
  import jumpjet:runtime/debug;
  import jumpjet:runtime/audio;
  import jumpjet:runtime/input;
  import jumpjet:runtime/gpu;
  import jumpjet:runtime/storage;
  import jumpjet:runtime/window;

  export guest;
}
