[package]
identifier = "{{ identifier }}"
version = "0.1.0"
type = "game"
author = ""

[runtime]
version = "{{ runtime_version }}"

[game.build]
pre = "npm run build"
entrypoint = "./dist/game.wasm" # The built wasm component to package
# assets = "./assets" # Optional: data files shipped with your game (mounted as local storage)
output = "./bin" # Jumpjet's build output

[bundle]
name = "{{ name }}"

[dependencies]
three = "165.0"
